### ISSUE TITLE
运行evaler/infer.py 时报错

### ISSUE THREAD

**Issue by sandy-ssdut** [feymanpriv/DOLG#4]
错误堆栈为：

Traceback (most recent call last):
  File "evaler/infer.py", line 119, in main_multicard
    data =  extract(im, model)
  File "evaler/infer.py", line 62, in extract
    global_feature = model(input_data)
  File "/home/tiger/workspace/anaconda/envs/DOLG/lib/python3.6/site-packages/torch/nn/modules/module.py", line 532, in __call__
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 1 required positional argument: 'targets'

**Comment by specular-zxy** [comment]
我也遇到了同样的错误，请问您解决了这个问题吗？

**Comment by sd0809** [comment]
同，请问楼主解决了吗？

**Comment by Pudge-tao** [comment]
> 同，请问楼主解决了吗？

你们解决了吗

**Comment by sd0809** [comment]
> 

arcface loss 需要同时输入数据和标签，源代码漏了标签。

**Comment by Pudge-tao** [comment]
> > 
> 
> arcface loss 需要同时输入数据和标签，源代码漏了标签。

推理的时候没有标签怎么办

**Comment by mennanyang** [comment]
> > 
> 
> arcface loss 需要同时输入数据和标签，源代码漏了标签。

请问你解决了吗

**Comment by sd0809** [comment]
> > > 
> > 
> > 
> > arcface loss 需要同时输入数据和标签，源代码漏了标签。
> 
> 请问你解决了吗

我推理的时候只需要模型最后的feature，所以我推理的时候标签是随机给的
